// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ewseahslovqxkgreehky.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV3c2VhaHNsb3ZxeGtncmVlaGt5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMxNjUxNzIsImV4cCI6MjA2ODc0MTE3Mn0.uqvOxSKv0BN2n-XFgJ6FKjcwLeAkFMI0EtdSwdM4OiQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});